# Install specific versions of libraries that are loaded in .Rprofile: 
# https://github.com/finmason2108/FinMason-Analytics/blob/1d61d092886af439cdadb00cc4bd005dff52a891/dev/OneByOne/NewArc/.Rprofile#L197-L200
install.packages('https://cran.r-project.org/src/contrib/Archive/devtools/devtools_2.4.4.tar.gz', repos=NULL, type="source")
require(devtools)

# Install specific versions of libraries
repo_url<- "http://cran.us.r-project.org"

install_version('argparse', version = '2.0.0', repos = repo_url)
install_version('testthat', version = '2.0.0', repos = repo_url)
install_version('data.table', version = '1.10.4-3', repos = repo_url)
install_version('DBI', version = '1.0.0', repos = repo_url)
install_version('doParallel', version = '1.0.11', repos = repo_url)
install_version('e1071', version = '1.6-8', repos = repo_url)
install_version('foreach', version = '1.4.4', repos = repo_url)
install_version('ggplot2', version = '3.1.0', repos = repo_url)
install_version('ini', version = '0.3.1', repos = repo_url)
install_version('jsonlite', version = '1.5', repos = repo_url)
install_version('lubridate', version = '1.7.4', repos = repo_url)
install_version('plyr', version = '1.8.4', repos = repo_url)
install_version('Quandl', version = '2.9.1', repos = repo_url)
install_version('quantmod', version = '0.4-11', repos = repo_url)
install_version('randomForest', version = '4.6-12', repos = repo_url)
install_version('Rcpp', version = '1.0.1', repos = repo_url)
install_version('dplyr', version = '0.8.0.1', repos = repo_url)
install_version('DT', version = '0.2', repos = repo_url)
install_version('RCurl', version = '1.95-4.8', repos = repo_url)
install_version('reshape', version = '0.8.6', repos = repo_url)
install_version('reshape2', version = '1.4.3', repos = repo_url)
install_version('rlang', version =  '0.3.3', repos = repo_url)
install_version('rpart', version = '4.1-10', repos = repo_url)
install_version('RPostgreSQL', version = '0.4-1', repos = repo_url)
install_version('RPostgres', version = '1.1.1', repos = repo_url)
install_version('stringi', version = '1.2.4', repos = repo_url)
install_version('stringr', version = '1.2.0', repos = repo_url)
install_version('timeDate', version = '3042.101', repos = repo_url)
install_version('XML', version = '3.98-1.16', repos = repo_url)
install_version('xts', version = '0.10-0', repos = repo_url)
install_version('zoo', version = '1.8-5', repos = repo_url)
install_version('tidyr', version = '0.8.3', repos = repo_url)
install_version('tibble', version = '2.1.1', repos = repo_url)
install_version('bizdays', version = '1.0.6', repos = repo_url)
install_version('xml2', version = '1.2.0', repos = repo_url)
install_version('rmarkdown', version =  '1.18', repos = repo_url)
install_version('covr', version =  '3.2.1', repos = repo_url)
install_version('bizdays', version =  '1.0.6', repos = repo_url)
install_version('aws.s3', version =  '0.3.21', repos = repo_url)
install.packages('png', version = '0.1-7', repos = repo_url)
install_version('rJava', version = '0.9-12', repos = repo_url)
install_version('memoise', version =  '1.1.0', repos = repo_url)
install_version('jsonify', version = '1.2.1', repos = repo_url)
install_version('openxlsx', version =  '4.2.4', repos = repo_url)
install_version('readxl', version =  '1.4.0', repos = repo_url)

